export default {
	LOGIN_START: 'LOGIN_START',
	LOGIN_FINISH: 'LOGIN_FINISH',
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGOUT_START: 'LOGOUT_START',
	LOGOUT_FINISH: 'LOGOUT_FINISH',
	LOGOUT_ERROR: 'LOGOUT_ERROR',
	REGISTER_START: 'REGISTER_START',
	REGISTER_FINISH: 'REGISTER_FINISH',
	REGISTER_ERROR: 'REGISTER_ERROR',
	CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
	CONFIRM_EMAIL_FINISH: 'CONFIRM_EMAIL_FINISH',
	CONFIRM_EMAIL_ERROR: 'CONFIRM_EMAIL_ERROR',
};
