export default {
	AUTH_USER_START: 'AUTH_USER_START',
	AUTH_USER_FINISH: 'AUTH_USER_FINISH',
	AUTH_USER_ERROR: 'AUTH_USER_ERROR',
	REGISTER_START: 'REGISTER_START',
	REGISTER_FINISH: 'REGISTER_FINISH',
	REGISTER_ERROR: 'REGISTER_ERROR',
	CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
	CONFIRM_EMAIL_FINISH: 'CONFIRM_EMAIL_FINISH',
	CONFIRM_EMAIL_ERROR: 'CONFIRM_EMAIL_ERROR',
};
